name: Build and Dockerize Java App

on:
  push:
    branches:
      - main
      - 'f_*'
  pull_request:
    branches:
      - main
      - 'f_*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package --no-transfer-progress

      - name: Build Docker Image
        run: docker build -t devsecops-github .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker tag devsecops-github ohpygod/devsecops_github:latest && docker push ohpygod/devsecops_github:latest
