name: Dockerhub Push

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      docker_repo:
        required: true
        type: string
    secrets:
      docker_user:
        required: true
      docker_pass:
        required: true

jobs:
  push:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.docker_user }}
          password: ${{ secrets.docker_pass }}
      - name: Push Docker Image
        run: |
          docker tag ${{ inputs.image_name }} ${{ inputs.docker_repo }}/${{ inputs.image_name }}:latest
          docker push "${{ inputs.docker_repo }}/${{ inputs.image_name }}:latest"
          docker tag ${{ inputs.image_name }} ${{ inputs.docker_repo }}/${{ inputs.image_name }}:${{ github.sha }}
          docker push "${{ inputs.docker_repo }}/${{ inputs.image_name }}:${{ github.sha }}"
          
          
